/* StageEtudiant — complete French diploma/education levels list.
 * Used in: register, profile, offer creation, search filters, AI search, admin.
 */
export const DIPLOMA_LEVELS = [
  "Sans diplôme requis",
  "Collège",
  "Stage de 3e",
  "CAP",
  "BEP",
  "Bac général",
  "Bac technologique",
  "Bac professionnel",
  "Mention complémentaire",
  "BP",
  "BMA",
  "Bac +1",
  "BTS",
  "BTSA",
  "DUT",
  "BUT",
  "DEUST",
  "Licence",
  "Licence professionnelle",
  "Bachelor",
  "Bac +2",
  "Bac +3",
  "Bac +4",
  "Master 1",
  "Master 2",
  "Bac +5",
  "Diplôme d'ingénieur",
  "MBA",
  "Mastère spécialisé",
  "Doctorat",
  "Reconversion professionnelle",
  "Formation courte",
  "Formation adulte",
];
